# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

toeplitzXZ <- function(X, acf) {
    .Call('Toeplitz_DurbinLevinson_XZ', PACKAGE = 'Toeplitz', X, acf)
}

toeplitzZX <- function(Z, acf) {
    .Call('Toeplitz_DurbinLevinson_ZX', PACKAGE = 'Toeplitz', Z, acf)
}

DurbinLevinsonEigen <- function(X, Y, acf, calcMode = 1L) {
    .Call('Toeplitz_DurbinLevinson_Eigen', PACKAGE = 'Toeplitz', X, Y, acf, calcMode)
}

DurbinLevinsonBase <- function(X, Y, acf, calcMode = 1L) {
    .Call('Toeplitz_DurbinLevinson_Base', PACKAGE = 'Toeplitz', X, Y, acf, calcMode)
}

