#' @title Mean square displacement(MSD) of fractional Brownian motion(fBM) processes
#'
#' @description Return the MSD of fBM at series of timepoints.
#' @param tseq length \code{N} vector of timepoints
#' @param alpha Subdiffusion exponent of fBM process
#' @return Length \code{N} vector of MSD.
#' @details
#' MSD is a measure of the average distance particles travel, defined by
#' \deqn{
#' \textrm{MSD}_X(t) = E\left[X(t) - X(0)\right]^2
#' }{
#' E[X(t) - X(0)]^2
#' }
#' The MSD of fBM is given by:
#' \deqn{
#' \textrm{MSD}(t) = t^\alpha
#' }{
#' MSD(t) = t^\alpha
#' }
#' @examples
#' fbm.msd(tseq = 1:10, alpha = 0.8)
#' @note 
#' In order to simulate or inference some evenly-spaced fBM processes, ACF of fBM increments can be generated by 
#' combining \code{fbm.msd} and \code{msd2acf}.
#' @export
fbm.msd <- function(tseq, alpha) {
  tseq^alpha
}