# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Circulant_ctor <- function(N) {
    .Call(`_SuperGauss_Circulant_ctor`, N)
}

Circulant_set_acf <- function(pCirc, uacf) {
    invisible(.Call(`_SuperGauss_Circulant_set_acf`, pCirc, uacf))
}

Circulant_get_acf <- function(pCirc) {
    .Call(`_SuperGauss_Circulant_get_acf`, pCirc)
}

Circulant_set_psd <- function(pCirc, upsd) {
    invisible(.Call(`_SuperGauss_Circulant_set_psd`, pCirc, upsd))
}

Circulant_get_psd <- function(pCirc) {
    .Call(`_SuperGauss_Circulant_get_psd`, pCirc)
}

Circulant_has_acf <- function(pCirc) {
    .Call(`_SuperGauss_Circulant_has_acf`, pCirc)
}

Circulant_prod <- function(pCirc, X) {
    .Call(`_SuperGauss_Circulant_prod`, pCirc, X)
}

Circulant_solve <- function(pCirc, X) {
    .Call(`_SuperGauss_Circulant_solve`, pCirc, X)
}

Circulant_log_det <- function(pCirc) {
    .Call(`_SuperGauss_Circulant_log_det`, pCirc)
}

DurbinLevinson_XZ <- function(X, acf) {
    .Call(`_SuperGauss_DurbinLevinson_XZ`, X, acf)
}

DurbinLevinson_ZX <- function(Z, acf) {
    .Call(`_SuperGauss_DurbinLevinson_ZX`, Z, acf)
}

DurbinLevinson_Eigen <- function(X, Y, acf, calcMode = 1L) {
    .Call(`_SuperGauss_DurbinLevinson_Eigen`, X, Y, acf, calcMode)
}

DurbinLevinson_Base <- function(X, Y, acf, calcMode = 1L) {
    .Call(`_SuperGauss_DurbinLevinson_Base`, X, Y, acf, calcMode)
}

real_fft <- function(x, inverse = FALSE) {
    .Call(`_SuperGauss_real_fft`, x, inverse)
}

even_fft <- function(x, inverse = FALSE) {
    .Call(`_SuperGauss_even_fft`, x, inverse)
}

NormalCirculant_ctor <- function(N) {
    .Call(`_SuperGauss_NormalCirculant_ctor`, N)
}

NormalCirculant_logdens <- function(pNCt, z, uacf) {
    .Call(`_SuperGauss_NormalCirculant_logdens`, pNCt, z, uacf)
}

NormalCirculant_grad_full <- function(pNCt, z, uacf, calc_dldz = TRUE, calc_dldu = TRUE) {
    .Call(`_SuperGauss_NormalCirculant_grad_full`, pNCt, z, uacf, calc_dldz, calc_dldu)
}

.NormalToeplitz_constructor <- function(N) {
    .Call(`_SuperGauss_NormalToeplitz_constructor`, N)
}

.NormalToeplitz_logdens <- function(NTz_ptr, z, acf) {
    .Call(`_SuperGauss_NormalToeplitz_logdens`, NTz_ptr, z, acf)
}

.NormalToeplitz_grad <- function(NTz_ptr, z, dzdt, acf, dadt, n_theta) {
    .Call(`_SuperGauss_NormalToeplitz_grad`, NTz_ptr, z, dzdt, acf, dadt, n_theta)
}

.NormalToeplitz_hess <- function(NTz_ptr, z, dzdt, d2zdt, acf, dadt, d2adt, n_theta) {
    .Call(`_SuperGauss_NormalToeplitz_hess`, NTz_ptr, z, dzdt, d2zdt, acf, dadt, d2adt, n_theta)
}

.NormalToeplitz_grad_full <- function(NTz_ptr, z, acf, calc_dldz = TRUE, calc_dlda = TRUE) {
    .Call(`_SuperGauss_NormalToeplitz_grad_full`, NTz_ptr, z, acf, calc_dldz, calc_dlda)
}

.PCG_constructor <- function(n) {
    .Call(`_SuperGauss_PCG_constructor`, n)
}

.PCG_solve <- function(PCG_ptr, acf, y, tol) {
    .Call(`_SuperGauss_PCG_solve`, PCG_ptr, acf, y, tol)
}

.Toeplitz_constructor <- function(n) {
    .Call(`_SuperGauss_Toeplitz_constructor`, n)
}

.Toeplitz_set_acf <- function(Toep_ptr, acf) {
    invisible(.Call(`_SuperGauss_Toeplitz_set_acf`, Toep_ptr, acf))
}

.Toeplitz_get_acf <- function(Toep_ptr) {
    .Call(`_SuperGauss_Toeplitz_get_acf`, Toep_ptr)
}

.Toeplitz_prod <- function(Toep_ptr, X) {
    .Call(`_SuperGauss_Toeplitz_prod`, Toep_ptr, X)
}

.Toeplitz_solve <- function(Toep_ptr, X) {
    .Call(`_SuperGauss_Toeplitz_solve`, Toep_ptr, X)
}

.Toeplitz_log_det <- function(Toep_ptr) {
    .Call(`_SuperGauss_Toeplitz_log_det`, Toep_ptr)
}

.Toeplitz_trace_grad <- function(Toep_ptr, acf2) {
    .Call(`_SuperGauss_Toeplitz_trace_grad`, Toep_ptr, acf2)
}

.Toeplitz_trace_hess <- function(Toep_ptr, acf2, acf3) {
    .Call(`_SuperGauss_Toeplitz_traceT4`, Toep_ptr, acf2, acf3)
}

.Toeplitz_has_acf <- function(Toep_ptr) {
    .Call(`_SuperGauss_Toeplitz_has_acf`, Toep_ptr)
}

