# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Circulant_ctor <- function(N) {
    .Call(`_SuperGauss_Circulant_ctor`, N)
}

Circulant_set_acf <- function(pCirc, uacf) {
    invisible(.Call(`_SuperGauss_Circulant_set_acf`, pCirc, uacf))
}

Circulant_get_acf <- function(pCirc) {
    .Call(`_SuperGauss_Circulant_get_acf`, pCirc)
}

Circulant_set_psd <- function(pCirc, upsd) {
    invisible(.Call(`_SuperGauss_Circulant_set_psd`, pCirc, upsd))
}

Circulant_get_psd <- function(pCirc) {
    .Call(`_SuperGauss_Circulant_get_psd`, pCirc)
}

Circulant_has_acf <- function(pCirc) {
    .Call(`_SuperGauss_Circulant_has_acf`, pCirc)
}

Circulant_prod <- function(pCirc, X) {
    .Call(`_SuperGauss_Circulant_prod`, pCirc, X)
}

Circulant_solve <- function(pCirc, X) {
    .Call(`_SuperGauss_Circulant_solve`, pCirc, X)
}

Circulant_log_det <- function(pCirc) {
    .Call(`_SuperGauss_Circulant_log_det`, pCirc)
}

DurbinLevinson_XZ <- function(X, acf) {
    .Call(`_SuperGauss_DurbinLevinson_XZ`, X, acf)
}

DurbinLevinson_ZX <- function(Z, acf) {
    .Call(`_SuperGauss_DurbinLevinson_ZX`, Z, acf)
}

DurbinLevinson_crossprod <- function(X, Y, acf, calc_mode = 1L) {
    .Call(`_SuperGauss_DurbinLevinson_crossprod`, X, Y, acf, calc_mode)
}

DurbinLevinson_solve <- function(X, acf) {
    .Call(`_SuperGauss_DurbinLevinson_solve`, X, acf)
}

real_fft <- function(x, inverse = FALSE) {
    .Call(`_SuperGauss_real_fft`, x, inverse)
}

even_fft <- function(x, inverse = FALSE) {
    .Call(`_SuperGauss_even_fft`, x, inverse)
}

NormalCirculant_ctor <- function(N) {
    .Call(`_SuperGauss_NormalCirculant_ctor`, N)
}

NormalCirculant_logdens <- function(pNCt, z, uacf) {
    .Call(`_SuperGauss_NormalCirculant_logdens`, pNCt, z, uacf)
}

NormalCirculant_grad_full <- function(pNCt, z, uacf, calc_dldz = TRUE, calc_dldu = TRUE) {
    .Call(`_SuperGauss_NormalCirculant_grad_full`, pNCt, z, uacf, calc_dldz, calc_dldu)
}

NormalToeplitz_ctor <- function(N) {
    .Call(`_SuperGauss_NormalToeplitz_ctor`, N)
}

NormalToeplitz_logdens <- function(NTz_ptr, z, acf) {
    .Call(`_SuperGauss_NormalToeplitz_logdens`, NTz_ptr, z, acf)
}

NormalToeplitz_grad <- function(NTz_ptr, z, dzdt, acf, dadt, full_out = FALSE) {
    .Call(`_SuperGauss_NormalToeplitz_grad`, NTz_ptr, z, dzdt, acf, dadt, full_out)
}

NormalToeplitz_hess <- function(NTz_ptr, z, dzdt, d2zdt, acf, dadt, d2adt, full_out = FALSE) {
    .Call(`_SuperGauss_NormalToeplitz_hess`, NTz_ptr, z, dzdt, d2zdt, acf, dadt, d2adt, full_out)
}

NormalToeplitz_grad_full <- function(NTz_ptr, z, acf, calc_dldz = TRUE, calc_dlda = TRUE) {
    .Call(`_SuperGauss_NormalToeplitz_grad_full`, NTz_ptr, z, acf, calc_dldz, calc_dlda)
}

PCG_ctor <- function(N) {
    .Call(`_SuperGauss_PCG_ctor`, N)
}

PCG_solve <- function(pPTz, acf, y, tol) {
    .Call(`_SuperGauss_PCG_solve`, pPTz, acf, y, tol)
}

Toeplitz_ctor <- function(N) {
    .Call(`_SuperGauss_Toeplitz_ctor`, N)
}

Toeplitz_set_acf <- function(pToep, acf) {
    invisible(.Call(`_SuperGauss_Toeplitz_set_acf`, pToep, acf))
}

Toeplitz_get_acf <- function(pToep) {
    .Call(`_SuperGauss_Toeplitz_get_acf`, pToep)
}

Toeplitz_prod <- function(pToep, X) {
    .Call(`_SuperGauss_Toeplitz_prod`, pToep, X)
}

Toeplitz_solve <- function(pToep, X) {
    .Call(`_SuperGauss_Toeplitz_solve`, pToep, X)
}

Toeplitz_log_det <- function(pToep) {
    .Call(`_SuperGauss_Toeplitz_log_det`, pToep)
}

Toeplitz_trace_grad <- function(pToep, acf0) {
    .Call(`_SuperGauss_Toeplitz_trace_grad`, pToep, acf0)
}

Toeplitz_trace_hess <- function(pToep, acf1, acf2) {
    .Call(`_SuperGauss_Toeplitz_trace_hess`, pToep, acf1, acf2)
}

Toeplitz_has_acf <- function(pToep) {
    .Call(`_SuperGauss_Toeplitz_has_acf`, pToep)
}

